apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test"
  annotations:
    github.com/project-slug: 'Prakashja/backstage' #name of the terraform repo
    backstage.io/techdocs-ref: dir:.
  title: 'IA for Instance Automation'
  description: An example of a Instance Creation.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental